.TH WS63FLASH 1 "August 2025" "0.2.4"
.SH NAME
ws63sign \- machine code signing tool for Hisilicon WS63

.SH SYNOPSIS
.B ws63sign
[\fIOPTION...\fR] -- \fIINPUT\fR [\fIOUTPUT\fR]

.SH OPTIONS
.TP
.B \-o, --out
specify the output file (defaults to a.signed)

.TP
.B \-?, --help
give this help list

.TP
.B \--version
print program version

.SH BUGS
Report bugs to <gongzl@stu.hebust.edu.cn>.

.SH COPYRIGHT
Copyright (C) 2025  Gong Zhile.
This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
