.TH WS63FLASH 1 "October 2024" "0.2.0"
.SH NAME
ws63flash \- flashing utility for Hisilicon WS63

.SH SYNOPSIS
.B ws63flash
[\fIOPTION...\fR] --flash \fITTY FWPKG\fR [\fIBIN...\fR]

.B ws63flash
[\fIOPTION...\fR] --write \fITTY LOADERBOOT\fR [\fIBIN@ADDR...\fR]

.B ws63flash
[\fIOPTION...\fR] --erase \fITTY FWPKG\fR

.SH ACTIONS
.TP
.B \-f, --flash
flash a fwpkg file

.TP
.B \-w, --write
write bin(s) to specific address

.TP
.B \-e, --erase
erase the flash memory

.SH OPTIONS
.TP
.B \-b, --baud
set the flashing serial baudrate

.TP
.B \--late-baud
set the baudrate after loaderBoot (Available on Hi3863, NEW)

.TP
.B \-v, --verbose
verbosely output the interactions

.TP
.B \-?, --help
give this help list

.TP
.B \--version
print program version

.SH BUGS
Report bugs to <gongzl@stu.hebust.edu.cn>.

.SH COPYRIGHT
Copyright (C) 2024  Gong Zhile.
This is free software; see the source for copying conditions.  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
