name: MSYS2
on: [push, pull_request]

jobs:
  msys2-msys:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
          install: git autoconf automake groff gcc make zip
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          autoreconf -fi
          CC="gcc -static" ./configure
          make
          mkdir ws63flash
          cp src/ws63flash ws63flash
          cp /usr/bin/msys-2.0.dll ws63flash
      - uses: actions/upload-artifact@v4.4.0
        with:
          name: ws63flash-win32-msys
          path: ws63flash
